version: "3.8"
services:

    db:
        image: mysql
        container_name: db_docker_project
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_project
        restart: always
        depends_on:
            - db
        ports:
            - "8000:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: php
        container_name: www_docker_project
        ports:
          - "8743:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
networks:
    dev:

volumes:
    db-data: